### ISSUE TITLE
Migration of wiki-pages to repository

### ISSUE THREAD

**Issue by vipulgupta2048** [sugarlabs/i-can-read-activity#5]
**Description** 
- Sugar Labs Wiki has 345 pages of various activities. The documentation is getting difficult to manage and is not sustainable in the long run. 
- Hence the migration of the aforementioned wiki-pages to their GitHub repository are underway.
- This would benefit community members, contributors and users alike. Since having documentation on GitHub makes it easier to manage, edit, add, delete and even store. With its markdown based README.md system.

**Comment by vipulgupta2048** [comment]
#4 solves this issue. 
Created issue for future reference.

**Comment by quozl** [comment]
Issue by you seems redundant given we have a pull request by you.  Noisy for people subscribed to every repository.  Please don't think of an issue as a reservation.  Next time, please consider whether an issue must be added.  As a community we don't have the time and discipline to split discussions between an issue and a pull request; we tend to allow pull request comments to refer to the problem being solved.

**Comment by vipulgupta2048** [comment]
@quozl I deeply apologize for my actions, It won't be repeated again. 
Pull Requests only, issues only where required. Got it. :+1:  
> we tend to allow pull request comments to refer to the problem being solved.  

I tend to the same, but my motives were not to waste anybody's time. As said, it won't happen again. 
Thanks for pointing it out.
